import { embed } from 'ai'
import { createClient } from "@supabase/supabase-js";
import { supabase } from "./supabaseClient.js";
import type { RecommendedMovie, MovieAPI, RecommendationsByLLM } from "./types.js";
import { getRagPrompt } from "./utils.js"
import { generateText, Output } from 'ai';
import { z } from 'zod';
import { openai } from "@ai-sdk/openai";



const EMBEDDING_MODEL = getEnv('EMBEDDING_MODEL');


// function/Agent tool to retrieve movies by RAG from Supabase PostgreSQL vector DB
export async function retrieveSimilarMoviesByRAG(query:string) {

    // query to embeddingprompt
    const embeddingPrompt: string = `Movie characteristics description: ${query}`

    // query to embedding 
     const { embedding: queryEmbedding } = await embed({
            model: openai.embedding(EMBEDDING_MODEL),
            value: query,
            });
                    
    // RPC similarity search on vector_movie database
    console.log(`[NORMAL] I am sending request to supabase to use similarity search by special rpc function and match_movies function`)
    const { data, error } = await supabase.rpc("match_movies", {
      query_embedding: queryEmbedding,
      match_threshold: 0.7,
      match_count: 5
    });

    if (error) {
      throw error;
    }
    console.log(`[NORMAL] retrieved data`, data)
    // retrieved data array  ==> array transformation by map to more usable version of array on client site
    const receivedMovies: MovieAPI[]= data
    console.log(`[NORMAL] received movies`, receivedMovies)

    const moviesWithIndex: RecommendedMovie[] = receivedMovies.map((movie, index) => ({
      title: movie.title,
      year: movie.release_date ? movie.release_date.slice(0,4) : "unknown",
      poster_path: movie.poster_path,
      overview: movie.overview,
      index,
      isLast: index === receivedMovies.length - 1
    }));


    // prompt to change movie_overviews to recommendations - "human answer" answer by structured_output
    const contextString: string = JSON.stringify(moviesWithIndex.map(movie => ({
        title: movie.title,
        year: movie.year,
        overview: movie.overview,
        index: movie.index
    }))) 

    // create personalized reply based on data
    console.log(`[NORMAL] sending request to generate personalised answer`)
    console.log(`[NORMAL] user query: ${query} moviesArr: ${contextString}`)
    const result = await generateText({
        model: openai("gpt-4.1-nano"),
        output: Output.object({
            schema: z.object({
            recommendations: z
                .array(
                z.object({
                    index: z.number().int(),

                    recommendation: z
                    .string()
                    .describe(
                        "Personalized explanation in 3 to 4 sentences explaining why this movie matches the user's request.",
                    ),
                }),
                )
                .length(moviesWithIndex.length),
            }),
        }),

            prompt: `
            User request:
            ${query}

            Movies retrieved using vector similarity search:
            ${contextString}

            You are movie expert. For every provided movie, write a personalized recommendation explaining
            why it matches the user's request.

            Rules:
            - Return exactly one recommendation for every provided movie.
            - Keep the original movie index unchanged.
            - Each recommendation must contain 3 to 4 sentences.
            - Use only information from the provided movie context.
            - If no movies were provided, return an empty recommendations array.
            `,
            });

    console.log('[NORMAL] recommendations array generated by LLM:')
    console.log(result.output.recommendations);
    const recommendationArr: RecommendationsByLLM[] = result.output.recommendations
    

    // create new array of movies with recommendation of LLM, to recommended movies - here: const moviesWithIndex: RecommendedMovie[]
    const moviesWithRecommendations = moviesWithIndex.map(movie => {
    const matchingRecommendation = recommendationArr.find(
        item => item.index === movie.index
        )

        const { overview, ...movieWithoutOverview } = movie


        return {
        ...movieWithoutOverview,
        recommendation: matchingRecommendation?.recommendation ?? ""
        }
        })
      
    console.log('[NORMAL] Final data for client:', moviesWithRecommendations)


    // function return array of recommended movies
    return moviesWithRecommendations         
  }



// check and get ENVs 
function getEnv(name: string): string {
  const value = process.env[name];

  if (!value) {
    throw new Error(`[ERROR] Missing environment variable: ${name}`);
  }

  return value;
}